### ISSUE TITLE
Code for querying native ranges on kew?

### ISSUE THREAD

**Issue by cbud** [jannebor/plant_range_estimates#1]
Hi

Your code is useful for the MAXENT analysis, did you get a pipeline going for the native range estimates from Kew? I am coming at it from an invasive species perspective.

Hopefully

Chris Buddenhagen (New Zealand)

**Comment by cbud** [comment]
Found the other code- it was just that the link from the article went to here.

**Comment by cbud** [comment]
The article links here but the code for the Plants of World query is here: [https://github.com/jannebor/pow_workaround/blob/main/wgsrpd_regions.R]

**Comment by jannebor** [comment]
I've added the code and some examples to https://github.com/jannebor/plant_range_estimates/blob/main/functions/kew_distributions.R

**Comment by cbud** [comment]
Thanks a million
